#!/usr/bin/env bash
#
# update-plugins.sh — vendor MantisBT community plugins into plugins/.
#
# For each "<repo> <ref> [subdirs]" line in scripts/plugins.manifest this script:
#   1. resolves <ref> to an immutable commit SHA via `git ls-remote`
#   2. downloads that SHA's tarball from github.com/mantisbt-plugins/<repo>
#   3. extracts a pristine copy into plugins/ (byte-for-byte upstream@SHA). With
#      no subdirs the whole repo becomes plugins/<repo>; with a comma-separated
#      subdirs list (e.g. source-integration's Source,SourceGitlab,SourceGithub
#      or TelegramBot's TelegramBot) only those subdirs are vendored.
#   4. records repo / requested ref / resolved SHA / date in plugins/VENDOR.md
#
# Our local deltas (the Motives / TelegramBot patches and the Attachments
# .htaccess) are NOT applied here — they live in patches/ and are applied at
# build time by scripts/apply-plugin-patches.sh against the copied tree, so the
# vendored trees stay auditable against upstream. plugins/FieldDescriptions is
# repo-owned and never touched.
#
# Re-run this after editing scripts/plugins.manifest, then commit the changed
# plugins/ trees and plugins/VENDOR.md. See AGENTS.md for the full procedures.
#
# Usage: bash scripts/update-plugins.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
PLUGINS_DIR="${REPO_ROOT}/plugins"
MANIFEST="${SCRIPT_DIR}/plugins.manifest"
VENDOR_MD="${PLUGINS_DIR}/VENDOR.md"
ORG_URL="https://github.com/mantisbt-plugins"

if [[ ! -f "${MANIFEST}" ]]; then
    echo "error: manifest not found: ${MANIFEST}" >&2
    exit 1
fi

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "${WORK_DIR}"' EXIT

# Resolve a tag/branch/SHA ref to an immutable commit SHA.
resolve_sha() {
    local repo="$1" ref="$2"

    # Already a full 40-char commit SHA — use it verbatim.
    if [[ "${ref}" =~ ^[0-9a-fA-F]{40}$ ]]; then
        echo "${ref}"
        return
    fi

    local out
    out="$(git ls-remote "${ORG_URL}/${repo}.git" "${ref}")"
    if [[ -z "${out}" ]]; then
        echo "error: could not resolve ref '${ref}' for ${repo}" >&2
        exit 1
    fi

    # Prefer the dereferenced tag object (refs/tags/<ref>^{}) so annotated tags
    # resolve to the underlying commit; otherwise take the first match.
    local sha
    sha="$(echo "${out}" | awk '/\^\{\}$/{print $1; exit}')"
    if [[ -z "${sha}" ]]; then
        sha="$(echo "${out}" | awk 'NR==1{print $1}')"
    fi
    echo "${sha}"
}

# Download <repo>@<sha>'s tarball and extract it (stripped) into $1.
fetch_tree() {
    local repo="$1" sha="$2" dest="$3"
    mkdir -p "${dest}"
    curl -fSL "${ORG_URL}/${repo}/tarball/${sha}" -o "${WORK_DIR}/plugin.tar.gz"
    tar -xz --strip-components=1 -f "${WORK_DIR}/plugin.tar.gz" -C "${dest}"
    rm -f "${WORK_DIR}/plugin.tar.gz"
}

mkdir -p "${PLUGINS_DIR}"

# Accumulate provenance rows, written to VENDOR.md at the end.
VENDOR_ROWS=""
TODAY="$(date -u +%Y-%m-%d)"

while IFS= read -r line || [[ -n "${line}" ]]; do
    # Strip inline/whole-line comments, then split into fields. `read` trims
    # surrounding whitespace, so blank and comment-only lines yield an empty repo.
    # The optional third field is a comma-separated list of subdirs to vendor
    # (for repos that ship several plugins, or carry the plugin in a subdir);
    # empty means the whole repo is the plugin.
    line="${line%%#*}"
    read -r repo ref subdirs _ <<< "${line}"
    [[ -z "${repo}" ]] && continue
    if [[ -z "${ref}" ]]; then
        echo "error: malformed manifest line (missing ref): '${line}'" >&2
        exit 1
    fi

    echo ">> ${repo} @ ${ref}"
    sha="$(resolve_sha "${repo}" "${ref}")"
    echo "   resolved to ${sha}"

    vendored=""
    if [[ -n "${subdirs}" ]]; then
        # Extract to a temp dir and copy out only the named subdir(s).
        extract_dir="${WORK_DIR}/extract"
        rm -rf "${extract_dir}"
        fetch_tree "${repo}" "${sha}" "${extract_dir}"
        IFS=',' read -ra sub_list <<< "${subdirs}"
        for sub in "${sub_list[@]}"; do
            rm -rf "${PLUGINS_DIR:?}/${sub}"
            cp -r "${extract_dir}/${sub}" "${PLUGINS_DIR}/${sub}"
            vendored="${vendored}${vendored:+, }${sub}"
        done
    else
        # Whole repo is the plugin; extract straight into place.
        rm -rf "${PLUGINS_DIR:?}/${repo}"
        fetch_tree "${repo}" "${sha}" "${PLUGINS_DIR}/${repo}"
        vendored="${repo}"
    fi
    echo "   vendored: ${vendored}"

    VENDOR_ROWS="${VENDOR_ROWS}| \`${repo}\` | \`${ref}\` | \`${sha}\` | ${TODAY} |"$'\n'
done < "${MANIFEST}"

# Write the provenance record. The static header is kept as plain Markdown in a
# non-interpolating here-doc; only the accumulated rows are appended.
cat <<'EOF' > "${VENDOR_MD}"
# Vendored plugin provenance

This file is generated by `scripts/update-plugins.sh`. It records, for each
vendored community plugin, the upstream repository, the ref requested in
`scripts/plugins.manifest`, the immutable commit SHA that ref resolved to, and
the date it was vendored. All repos live under
<https://github.com/mantisbt-plugins>.

The trees under `plugins/` are pristine `upstream@SHA` copies. Our local deltas
are kept separately in `patches/` and applied at build time by
`scripts/apply-plugin-patches.sh`. `plugins/FieldDescriptions` is repo-owned and
not listed here.

| Repo | Requested ref | Resolved SHA | Vendored |
|---|---|---|---|
EOF
printf '%s' "${VENDOR_ROWS}" >> "${VENDOR_MD}"

echo
echo "Done. Vendored trees written under ${PLUGINS_DIR} and provenance to ${VENDOR_MD}."
echo "Review 'git status' / 'git diff' and commit the results."
